# Generated by Django 4.2.7 on 2025-07-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Educação',
                'verbose_name_plural': 'Educação',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, help_text='Deixe em branco se ainda trabalha aqui', null=True)),
                ('descricao', models.TextField()),
                ('tecnologias', models.CharField(help_text='Separadas por vírgula', max_length=200)),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('bio', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tecnologias', models.CharField(max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('destaque', models.BooleanField(default=False)),
                ('data_criacao', models.DateField()),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools & Others'), ('soft', 'Soft Skills')], max_length=20)),
                ('nivel', models.IntegerField(default=50, help_text='0-100')),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone (ex: python, django)', max_length=50)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
    ]
